In [1]:
    # 数据处理
import pandas as pd
import numpy as np
np.set_printoptions(precision=3)
     
    # 绘图
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df1=pd.read_excel('data.xlsx',index_col='时间')

In [3]:
from sklearn import preprocessing
df = preprocessing.scale(df1)
df

array([[ 1.228,  0.73 ,  0.5  ,  1.442,  1.727,  1.731,  1.661],
       [ 0.389,  1.095,  0.959, -0.933, -0.453, -0.54 , -0.518],
       [-0.09 , -0.365,  0.21 ,  0.424, -0.622, -0.573, -0.173],
       [-1.527, -1.461, -1.669, -0.933, -0.652, -0.618, -0.97 ]])

In [4]:
df=(df-df.min(axis=0))/(df.max(axis=0)-df.min(axis=0))
df

array([[1.   , 0.857, 0.826, 1.   , 1.   , 1.   , 1.   ],
       [0.696, 1.   , 1.   , 0.   , 0.084, 0.033, 0.172],
       [0.522, 0.429, 0.715, 0.571, 0.013, 0.019, 0.303],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ]])

In [53]:
p=df/df.sum()
p

array([[0.082, 0.07 , 0.067, 0.082, 0.082, 0.082, 0.082],
       [0.057, 0.082, 0.082, 0.   , 0.007, 0.003, 0.014],
       [0.043, 0.035, 0.058, 0.047, 0.001, 0.002, 0.025],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ]])

In [70]:
e=p*np.log(p)
e

E:\APP\Miniconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.
E:\APP\Miniconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in multiply
  """Entry point for launching an IPython kernel.


array([[-0.205, -0.186, -0.182, -0.205, -0.205, -0.205, -0.205],
       [-0.163, -0.205, -0.205,    nan, -0.034, -0.016, -0.06 ],
       [-0.135, -0.117, -0.166, -0.143, -0.007, -0.01 , -0.092],
       [   nan,    nan,    nan,    nan,    nan,    nan,    nan]])

In [73]:
arr=e
for row_idx in range(arr.shape[0]):
    for col_idx in range(arr.shape[1]):
        if np.isnan(arr[row_idx][col_idx]):
            arr[row_idx][col_idx] =0
e=arr
e

array([[-0.205, -0.186, -0.182, -0.205, -0.205, -0.205, -0.205],
       [-0.163, -0.205, -0.205,  0.   , -0.034, -0.016, -0.06 ],
       [-0.135, -0.117, -0.166, -0.143, -0.007, -0.01 , -0.092],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ]])

In [77]:
e=e.sum(axis=0)/(-np.log(7))
e

array([0.258, 0.261, 0.284, 0.179, 0.126, 0.119, 0.183])

In [79]:
d=1-e
d

array([0.742, 0.739, 0.716, 0.821, 0.874, 0.881, 0.817])

In [81]:
w=d/d.sum()
w

array([0.133, 0.132, 0.128, 0.147, 0.156, 0.158, 0.146])

In [20]:
import numpy as np

def ConsisTest(X):
    X = np.array(X)
    sum_X = X.sum(axis=0)
    (n, n) = X.shape
    sum_X = np.tile(sum_X, (n, 1))
    stand_X = X / sum_X

    sum_row = stand_X.sum(axis=1)

    print("算数平均法求权重的结果为：")
    print(sum_row / n)

    V, E = np.linalg.eig(X)
    max_value = np.max(V)
    max_v_index = np.argmax(V)
    max_eiv = E[:, max_v_index]
    stand_eiv = max_eiv / max_eiv.sum()
    print("特征值法求权重的结果为：")
    print(stand_eiv)
    print("———————————————————————————————")

    CI = (max_value - n) / (n - 1)
    RI = np.array([15, 0, 0, 0.52, 0.89, 1.12, 1.26, 1.36, 1.41, 1.46, 1.49, 1.52, 1.54, 1.56, 1.58, 1.59])
    CR = CI / RI[n]
    if CR < 0.1:
        print("CR=", CR, "，小于0.1，通过一致性检验")
        print(max_value)
    else:
        print("CR=", CR, "，大于等于0.1，没有通过一致性检验，请修改判断矩阵")
    return None

X = [[1, 5, 5, 2, 2, 4, 5],
     [1/5, 1, 1, 1/4, 1/5, 2, 1],
     [1/5, 1, 1, 1, 1, 2, 3],
     [1/2, 4, 1, 1, 1, 3, 4],
     [1/2, 5, 1, 1, 1, 3, 4],
     [1/4, 1/2, 1/2, 1/3, 1/3, 1, 3],
     [1/5, 1, 1/3, 1/4, 1/4, 1/3,1]]
ConsisTest(X)

算数平均法求权重的结果为：
[0.333 0.069 0.121 0.177 0.185 0.07  0.045]
特征值法求权重的结果为：
[0.336+0.j 0.07 +0.j 0.119+0.j 0.176+0.j 0.186+0.j 0.068+0.j 0.045+0.j]
———————————————————————————————
CR= (0.05329455945231815+0j) ，小于0.1，通过一致性检验
(7.434883605130916+0j)
